# Generated by Django 2.0.2 on 2018-03-25 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_delivery', models.CharField(help_text='100 characters max.', max_length=100)),
                ('smoking', models.CharField(help_text='100 characters max.', max_length=100)),
                ('alcohol', models.CharField(help_text='100 characters max.', max_length=100)),
                ('wifi', models.CharField(help_text='100 characters max.', max_length=100)),
                ('valetparking', models.CharField(help_text='100 characters max.', max_length=100)),
                ('rooftop', models.CharField(help_text='100 characters max.', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
