# Generated by Django 2.0.2 on 2018-03-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CusineTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=40)),
                ('starttime', models.CharField(max_length=40)),
                ('endtime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('homedelivery', models.CharField(max_length=5)),
                ('smoking', models.CharField(max_length=5)),
                ('alcohol', models.CharField(max_length=5)),
                ('wifi', models.CharField(max_length=5)),
                ('valetparking', models.CharField(max_length=5)),
                ('rooftop', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=40)),
                ('timing', models.CharField(max_length=40)),
                ('starttime', models.CharField(max_length=40)),
                ('endtime', models.CharField(max_length=40)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Restaurant'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Restaurant'),
        ),
    ]
